model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: segmentation
    image_size_x: 64
    image_size_y: 64
    channels: 3
    concat_mode: true
    cond_stage_trainable: true
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 6
        out_channels: 3
        model_channels: 128
        attention_resolutions:
        - 32
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 4
        - 8
        num_heads: 8
    
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ckpt_path: /raid/home/follels/Documents/latent-diffusion/logs/2022-10-17T10-50-26_ae_dce_mip/checkpoints/epoch=000188.ckpt
        ddconfig:
          attn_type: none
          double_z: false
          z_channels: 3
          resolution: 512
          in_channels: 1
          out_ch: 1
          ch: 32
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    
    cond_stage_config:
      target: ldm.modules.encoders.modules.SpatialRescaler
      params:
        n_stages: 2
        in_channels: 1
        out_channels: 3

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: false
    num_workers: 10
    train:
      target: ldm.data.dce_mip.DCEMipMaskTrain
    validation:
      target: ldm.data.dce_mip.DCEMipMaskValidation

lightning:
  trainer:
    log_every_n_steps: 20
    progress_bar_refresh_rate: 50
    gpus: "0,"
