model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 1000
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: class_label
    # image_size: 128
    image_size_x: 64
    image_size_y: 64
    channels: 3
    concat_mode: false
    cond_stage_trainable: true
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 128
        in_channels: 3  
        out_channels: 3 
        model_channels: 32
        attention_resolutions:
        - 32
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 4
        - 8
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ckpt_path: /home/hpc/iwi5/iwi5044h/latent-diffusion/logs/2022-10-08T14-07-28_ae_nih/checkpoints/epoch=000103.ckpt
        ddconfig:
          attn_type: none
          double_z: false
          z_channels: 3
          resolution: 512
          in_channels: 1
          out_ch: 1
          ch: 32
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        embed_dim: 512
        key: class_label

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    wrap: false
    num_workers: 16
    train:
      target: ldm.data.nih_chest_xray.NIHTrain
    validation:
      target: ldm.data.nih_chest_xray.NIHValidation

lightning:
  trainer:
    log_every_n_steps: 50
    progress_bar_refresh_rate: 50
    gpus: "0," # "0,1,2,3,4,5,6,7"
    # accelerator: ddp